config {
    type: "table",
    database: "curated-project-id",
    assertions: {
    nonNull: ["lab_report_id","patient_id","test_timestamp","lab_report_uri"],
    uniqueKey:["lab_report_id"]
    }
}

SELECT
  t1.*,
  t2.patient_id,
  t2.test_timestamp
FROM
  `projectid.dataset.lab_report_object_table_1` AS t1
LEFT JOIN
  `projectid.dataset.lab_report_data` AS t2
ON
  t1.lab_report_id = t2.lab_report_id 
