config {
    type: "table",
    assertions: {
    nonNull: ["test_timestamp"]
  }
}

SELECT
  test_timestamp,
  DATE(test_timestamp) AS date,
  EXTRACT(DAYOFWEEK FROM test_timestamp) AS day_of_week,
  EXTRACT(WEEK FROM test_timestamp) AS calendar_week_number,
  EXTRACT(MONTH FROM test_timestamp) AS calendar_month_number,
  FORMAT_DATE('%B', DATE(test_timestamp)) AS calendar_month_name,
  EXTRACT(QUARTER FROM test_timestamp) AS calendar_quarter_number,
  EXTRACT(YEAR FROM test_timestamp) AS calendar_year_number,
  create_timestamp as CURRENT_TIMESTAMP
FROM
  projectid.dataset.lab_report_data 