name: CF Invoker Workflow
description: CF Invoker Workflow

on:
  workflow_run:
    workflows: [Workflow 1]
    types: [completed]
    # branches: [main]

  # push:
  #   branches: 
  #     - main
  #   paths: 
  #     - 'temp_folder/**'

jobs:
  list_invoker_files:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.json_files.outputs.matrix }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get changed files
      id: changed-config-files
      uses: tj-actions/changed-files@v44
      with:
        files_yaml: |
          cf_config:
            - temp_folder/*.yaml
    
    - name: List all changed files
      id: json_files
      run: |
        configFiles=()
        mkdir artifacts
        for file in ${{ steps.changed-config-files.outputs.cf_config_all_changed_files }}; do
          ymlfile=$(basename "$file")
          json_file="${ymlfile%.yaml}.json"
          yq eval -o=json "$file" > "artifacts/${json_file}"
          configFiles+=("artifacts/${json_file}")
        done

        echo "configFiles: ${configFiles[@]}"
        echo "configFiles: ${!configFiles[@]}"
        
        jsonString=$( echo ${configFiles[@]}  | jq  -R -s -c 'sub("\n$";"") | split(" ")'  )
        echo "matrix=$jsonString"
        echo "matrix=$jsonString" >> $GITHUB_OUTPUT
    
    - name: upload-github artifact
      uses: actions/upload-artifact@v3
      with:
        name: cloud_function_artifacts
        path: artifacts
        retention-days: 1
  

  trigger_cf:
    needs: list_invoker_files
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        manifest: ${{ fromJson(needs.list_invoker_files.outputs.matrix) }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download  artifacts
      uses: actions/download-artifact@v3
      with:
        name: cloud_function_artifacts
        path: artifacts

    - name: JSON to variables
      uses: rgarcia-phi/json-to-variables@v1.1.0
      with:
        filename: '${{ matrix.manifest }}'
        prefix: v
    
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/551629814272/locations/global/workloadIdentityPools/hca-pool/providers/hca-provider'
        service_account: 'cicd-sa@hca-data-lake-poc.iam.gserviceaccount.com'
        id_token_audience: https://${{ env.v_cf_region }}-${{ env.v_cf_project_id }}.cloudfunctions.net/${{ env.v_cf_name }}
        token_format: 'id_token'

    # - name: GCP setup
    #   uses: 'google-github-actions/setup-gcloud@v2'
    
    - name: run code
      run: |
        jq -r '.json_data' "${{ matrix.manifest }}" > "file.json"

        CMD="curl -m 70 -X POST https://${{ env.v_cf_region }}-${{ env.v_cf_project_id }}.cloudfunctions.net/${{ env.v_cf_name }} \
        -H \"Authorization: Bearer ${{ steps.auth.outputs.id_token }}\" \
        -H \"Content-Type: application/json\" \
        -d @file.json"

        echo "CMD: $CMD"
        # eval $CMD
