name: Workflow 1

on:
  push:
    branches: 
      - main
    paths: 
      - '.github/workflows/workflow-1.yaml'

jobs:
  job-1:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - name: Example Step
        run: echo "Executing Workflow 1"
